fetcherArgs:
  closingDelay: 3 # 5
  dialogWaitDelay: 0.5 # 3
  inbetweenDelay: 0.2 # 2
  openingDelay: 6 # 4
  resendAmount: 60 # 1
  savePageAsIndexOnRightClick: 5 # 6
parser:
  delete_library_page_files_afterwards: 0
  parse_library_page: 0
  parse_ri_music_db: 0
  run_fetcher: 0
tasks:
  convert: 1
  download: 1
  tag: 1
